<Project>

    <PropertyGroup>
        <OutputPath>$(MsBuildThisFileDirectory)/.Builds</OutputPath>
        <LangVersion>latest</LangVersion>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>Koneko</RootNamespace>
        <EnableBepinise>true</EnableBepinise>
    </PropertyGroup>

    <ItemGroup>
        <!--
        <Reference Include="PlayerRagdollMod">
            <HintPath>$(ModsPath)/PlayerRagdollMod.dll</HintPath>
        </Reference>
        -->
        <CvrModReference Include="PlayerRagdollMod"/>
    </ItemGroup>

</Project>
