<Project>
  <!-- Temporary hack: I don't have any Melons installed, this should be safe -->
  <Target Name="ConfigureMelonLocalModSearchPaths"
          AfterTargets="ResolveCvrInstallPath"
          BeforeTargets="ResolveCvrModReferences"
          Condition="'$(LoaderFlavor)' == 'MelonLoader'">
    <ItemGroup>
      <CvrModReference Update="PlayerRagdollMod">
        <SearchPath>$(CVRPath)\BepInEx\plugins</SearchPath>
      </CvrModReference>
    </ItemGroup>
  </Target>
</Project>