<Project Sdk="Microsoft.NET.Sdk;Cvr.Mod.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>CVRLimbsGrabber</AssemblyName>
    <AssemblyTitle>CVRLimbsGrabber</AssemblyTitle>
    <OutputPath Condition="'$(CompatOutputPath)' != ''">$(CompatOutputPath)</OutputPath>
    <EnableBepinise>false</EnableBepinise>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LimbGrabber.csproj">
      <Aliases>RealLimbGrabber,%(Aliases)</Aliases>
    </ProjectReference>
  </ItemGroup>
</Project>